### ISSUE TITLE
blackhole example throws error

### ISSUE THREAD

**Issue by mrbluecoat** [alblue/dnsmasq-example#1]
I tried your blackhole example but it throws this error when I add `0.0.0.0 example.com` to the bottom:

```
dnsmasq[7451]: bad option at line 9 of /etc/dnsmasq.d/blackhole.hosts
```

https://discourse.pi-hole.net/t/dnsmasq-bad-option-at-line-1/42546/4 edit seems to indicate your usage of `*.conf` in `blackhole.conf` would allow the hosts file to exist in the dnsmasq.d directory but it didn't work for me. Only solution was to move the hosts file outside of the dnsmasq.d directory and update the path in blackhole.conf accordingly

**Comment by alblue** [comment]
Yes, you'll note that in the `dnsmasq.conf` example, there is already the `*.conf` on the end of it, which means that you don't pick up other files. If you don't have this, you'll need to move non-conf files elsewhere.

https://github.com/alblue/dnsmasq-example/blob/main/dnsmasq.conf#L2
